### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by lordbyronknox** [lordbyronknox/Real-Estate-Web-Page#3]
missing closing tag

**Comment by HassanMansoor96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing pages](https://trello.com/c/BiHldqUi/14-testing-pages)

**Comment by lordbyronknox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing pages](https://trello.com/c/BiHldqUi/14-testing-pages)
